### ISSUE TITLE
Document that we rely on a newer libva

### ISSUE THREAD

**Issue by mripard** [bootlin/libva-v4l2-request#1]
Debian stable uses libva 1.7.3, and our current code doesn't work with it. An arch linux with a newer libva (2.1.0) works, so we need to document that.

**Comment by paulkocialkowski** [comment]
Making 2.0 the required version made my build fail. Both my Arch Linux and ALARM setups have 1.4.0 reported by pkg-config --version libva and our code builds fine. I've made that the required version for the build. What was the error with 1.7.3?

**Comment by paulkocialkowski** [comment]
Turns out the version major is offset by one between the lib and the API. We need at least API 2.1.0 so lib version 1.1.0. Just pushed the change!
